"""Historical context, original-language roots, and public-domain commentary.

The content lives in `lexicon.json`, not in this file. That separation is the
point: adding a note about a verse is a data change, and asking a contributor
to edit Python to make one is asking them to risk breaking an import over a
typo in a footnote. It also means the same file can be validated, diffed,
translated, or generated by a script without touching code.

Coverage is CURATED, not complete — these are hand-checked entries. Callers
must use `has_lexicon()` and say so when a passage has none, rather than
rendering an empty panel that implies the text has nothing worth noting.

To make coverage complete, ingest a Strong's-tagged text (STEPBible TAHOT and
TAGNT are CC-BY) keyed to the same reference labels. The shape below is
already what such an import would produce.
"""
from __future__ import annotations
import json
from pathlib import Path

DATA = Path(__file__).with_name("lexicon.json")

# One entry per reference label, e.g. "Philippians 4:6-7":
#   context     str            required — the historical setting
#   commentary  {source, text} optional — public domain only, always attributed
#   lemmas      [{word, translit, strongs, gloss, note}]
_REQUIRED_LEMMA_KEYS = {"word", "translit", "strongs", "gloss", "note"}


def _load(path: Path = DATA) -> dict[str, dict]:
    """Read the entries, and fail loudly rather than half-render.

    A missing or malformed lexicon is a packaging mistake, not a runtime
    condition to paper over. Returning {} here would make every passage in the
    app quietly claim it has no lexical data — a wrong answer that looks
    exactly like a correct one.
    """
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise SystemExit(f"lexicon data missing: {path}")
    except json.JSONDecodeError as e:
        raise SystemExit(f"lexicon data is not valid JSON: {path}\n  {e}")

    for label, entry in raw.items():
        if "context" not in entry:
            raise SystemExit(f"lexicon entry {label!r} has no 'context'")
        for lemma in entry.get("lemmas", []):
            missing = _REQUIRED_LEMMA_KEYS - lemma.keys()
            if missing:
                raise SystemExit(
                    f"lexicon entry {label!r} has a lemma missing {sorted(missing)}")
        c = entry.get("commentary")
        if c and not c.get("source"):
            raise SystemExit(f"lexicon entry {label!r} has commentary with no source")
    return raw


ENTRIES: dict[str, dict] = _load()
COVERAGE = len(ENTRIES)


def get(label: str) -> dict:
    return ENTRIES.get(label, {})


def has_lexicon(label: str) -> bool:
    return bool(ENTRIES.get(label, {}).get("lemmas"))
